development:
  port: 8080
  directory: ./
  database: ./ota.sql
  builds: ./builds
  templates: ./views

production:
  port: 8080
  directory: /var/lib/android_ota_manager
  database: /var/lib/android_ota_manager/ota.sql
  builds: /var/lib/android_ota_manager/builds
  templates: /var/lib/android_ota_manager/views
